# Imports
import numpy as np

# --- Constants for Pipeline ---
# Define critical vs. non-critical features (for custom MissingValueChecker)
CRITICAL_FEATURES = ["income", "age", "experience", "profession", "city", "state", "current_job_yrs", "current_house_yrs"]
NON_CRITICAL_FEATURES = ["married", "car_ownership", "house_ownership"]

# Define columns to format categorical labels as snake case (for custom SnakeCaseFormatter)
COLUMNS_FOR_SNAKE_CASING = ["profession", "city", "state"]

# Map binary categorical columns to boolean (for custom BooleanColumnTransformer)
BOOLEAN_COLUMN_MAPPINGS = {
    "married": {"married": True, "single": False},
    "car_ownership": {"yes": True, "no": False}
}

# Map profession to job stability tier (for custom JobStabilityTransformer)
JOB_STABILITY_MAP = {
    # Government and highly regulated roles with exceptional job security
    "civil_servant": "very_stable",
    "army_officer": "very_stable",
    "police_officer": "very_stable",
    "magistrate": "very_stable",
    "official": "very_stable",
    "air_traffic_controller": "very_stable",
    "firefighter": "very_stable",
    "librarian": "very_stable",
    
    # Licensed/regulated professionals with strong job security
    "physician": "stable",
    "surgeon": "stable",
    "dentist": "stable",
    "chartered_accountant": "stable",
    "civil_engineer": "stable",
    "mechanical_engineer": "stable",
    "chemical_engineer": "stable",
    "petroleum_engineer": "stable",
    "biomedical_engineer": "stable",
    "engineer": "stable",
    
    # Corporate roles with steady demand
    "software_developer": "moderate",
    "computer_hardware_engineer": "moderate",
    "financial_analyst": "moderate",
    "industrial_engineer": "moderate",
    "statistician": "moderate",
    "microbiologist": "moderate",
    "scientist": "moderate",
    "geologist": "moderate",
    "economist": "moderate",
    "technology_specialist": "moderate",
    "design_engineer": "moderate",
    "architect": "moderate",
    "surveyor": "moderate",
    "secretary": "moderate",
    "flight_attendant": "moderate",
    "hotel_manager": "moderate",
    "computer_operator": "moderate",
    "technician": "moderate",
    
    # Project-based or variable demand roles
    "web_designer": "variable",
    "fashion_designer": "variable",
    "graphic_designer": "variable",
    "designer": "variable",
    "consultant": "variable",
    "technical_writer": "variable",
    "artist": "variable",
    "comedian": "variable",
    "chef": "variable",
    "analyst": "variable",
    "psychologist": "variable",
    "drafter": "variable",
    "aviator": "variable",
    "politician": "variable",
    "lawyer": "variable"
}

# Map city to city tier (for custom CityTierTransformer)
CITY_TIER_MAP = {
    # Tier 1 cities
    "new_delhi": "tier_1",
    "navi_mumbai": "tier_1",
    "kolkata": "tier_1",
    "bangalore": "tier_1",
    "chennai": "tier_1",
    "hyderabad": "tier_1",
    "mumbai": "tier_1",
    "pune": "tier_1",
    "ahmedabad": "tier_1",
    "jaipur": "tier_1",
    "lucknow": "tier_1",
    "noida": "tier_1",
    "coimbatore": "tier_1",
    "surat": "tier_1",
    "nagpur": "tier_1",
    "kochi": "tier_1",
    "thiruvananthapuram": "tier_1",
    "kanpur": "tier_1",
    "patna": "tier_1",

    # Tier 2 cities
    "bhopal": "tier_2",
    "vijayawada": "tier_2",
    "indore": "tier_2",
    "jodhpur": "tier_2",
    "vadodara": "tier_2",
    "ludhiana": "tier_2",
    "madurai": "tier_2",
    "agra": "tier_2",
    "mysore[7][8][9]": "tier_2",
    "rajkot": "tier_2",
    "nashik": "tier_2",
    "amritsar": "tier_2",
    "ranchi": "tier_2",
    "chandigarh_city": "tier_2",
    "allahabad": "tier_2",
    "bhubaneswar": "tier_2",
    "varanasi": "tier_2",
    "jabalpur": "tier_2",
    "guwahati": "tier_2",
    "tiruppur": "tier_2",
    "raipur": "tier_2",
    "udaipur": "tier_2",
    "gwalior": "tier_2",

    # Tier 3 cities
    "vijayanagaram": "tier_3",
    "bulandshahr": "tier_3",
    "saharsa[29]": "tier_3",
    "hajipur[31]": "tier_3",
    "satara": "tier_3",
    "ongole": "tier_3",
    "bellary": "tier_3",
    "giridih": "tier_3",
    "hospet": "tier_3",
    "khammam": "tier_3",
    "danapur": "tier_3",
    "bareilly": "tier_3",
    "satna": "tier_3",
    "howrah": "tier_3",
    "thanjavur": "tier_3",
    "farrukhabad": "tier_3",
    "buxar[37]": "tier_3",
    "arrah": "tier_3",
    "thrissur": "tier_3",
    "proddatur": "tier_3",
    "bahraich": "tier_3",
    "nandyal": "tier_3",
    "siwan[32]": "tier_3",
    "barasat": "tier_3",
    "dhule": "tier_3",
    "begusarai": "tier_3",
    "khandwa": "tier_3",
    "guntakal": "tier_3",
    "latur": "tier_3",
    "karaikudi": "tier_3",

    # Unknown tier cities
    "rewa": "unknown",
    "parbhani": "unknown",
    "alappuzha": "unknown",
    "tiruchirappalli[10]": "unknown",
    "jalgaon": "unknown",
    "jamnagar": "unknown",
    "kota[6]": "unknown",
    "karimnagar": "unknown",
    "adoni": "unknown",
    "erode[17]": "unknown",
    "kollam": "unknown",
    "anantapuram[24]": "unknown",
    "kamarhati": "unknown",
    "bhusawal": "unknown",
    "sirsa": "unknown",
    "amaravati": "unknown",
    "secunderabad": "unknown",
    "ajmer": "unknown",
    "miryalaguda": "unknown",
    "ambattur": "unknown",
    "pondicherry": "unknown",
    "shimoga": "unknown",
    "gulbarga": "unknown",
    "saharanpur": "unknown",
    "gopalpur": "unknown",
    "amravati": "unknown",
    "udupi": "unknown",
    "aurangabad[39]": "unknown",
    "shimla": "unknown",
    "bidhannagar": "unknown",
    "purnia[26]": "unknown",
    "bijapur": "unknown",
    "patiala": "unknown",
    "malda": "unknown",
    "sagar": "unknown",
    "durgapur": "unknown",
    "junagadh": "unknown",
    "singrauli": "unknown",
    "agartala": "unknown",
    "hindupur": "unknown",
    "naihati": "unknown",
    "north_dumdum": "unknown",
    "panchkula": "unknown",
    "anantapur": "unknown",
    "serampore": "unknown",
    "bathinda": "unknown",
    "nadiad": "unknown",
    "haridwar": "unknown",
    "berhampur": "unknown",
    "jamshedpur": "unknown",
    "bidar": "unknown",
    "kottayam": "unknown",
    "solapur": "unknown",
    "suryapet": "unknown",
    "aizawl": "unknown",
    "asansol": "unknown",
    "deoghar": "unknown",
    "eluru[25]": "unknown",
    "ulhasnagar": "unknown",
    "aligarh": "unknown",
    "south_dumdum": "unknown",
    "berhampore": "unknown",
    "gandhinagar": "unknown",
    "sonipat": "unknown",
    "muzaffarpur": "unknown",
    "raichur": "unknown",
    "rajpur_sonarpur": "unknown",
    "ambarnath": "unknown",
    "katihar": "unknown",
    "kozhikode": "unknown",
    "vellore": "unknown",
    "malegaon": "unknown",
    "nagaon": "unknown",
    "srinagar": "unknown",
    "davanagere": "unknown",
    "bhagalpur": "unknown",
    "meerut": "unknown",
    "dindigul": "unknown",
    "bhatpara": "unknown",
    "ghaziabad": "unknown",
    "kulti": "unknown",
    "chapra": "unknown",
    "dibrugarh": "unknown",
    "panihati": "unknown",
    "bhiwandi": "unknown",
    "morbi": "unknown",
    "kalyan_dombivli": "unknown",
    "gorakhpur": "unknown",
    "panvel": "unknown",
    "siliguri": "unknown",
    "bongaigaon": "unknown",
    "ramgarh": "unknown",
    "ozhukarai": "unknown",
    "mirzapur": "unknown",
    "akola": "unknown",
    "motihari[34]": "unknown",
    "jalna": "unknown",
    "jalandhar": "unknown",
    "unnao": "unknown",
    "karnal": "unknown",
    "cuttack": "unknown",
    "ichalkaranji": "unknown",
    "warangal[11][12]": "unknown",
    "jhansi": "unknown",
    "narasaraopet": "unknown",
    "chinsurah": "unknown",
    "jehanabad[38]": "unknown",
    "dhanbad": "unknown",
    "gudivada": "unknown",
    "gandhidham": "unknown",
    "raiganj": "unknown",
    "kishanganj[35]": "unknown",
    "belgaum": "unknown",
    "tirupati[21][22]": "unknown",
    "tumkur": "unknown",
    "kurnool[18]": "unknown",
    "gurgaon": "unknown",
    "muzaffarnagar": "unknown",
    "aurangabad": "unknown",
    "bhavnagar": "unknown",
    "munger": "unknown",
    "tirunelveli": "unknown",
    "mango": "unknown",
    "kadapa[23]": "unknown",
    "khora,_ghaziabad": "unknown",
    "ambala": "unknown",
    "ratlam": "unknown",
    "surendranagar_dudhrej": "unknown",
    "delhi_city": "unknown",
    "hapur": "unknown",
    "rohtak": "unknown",
    "durg": "unknown",
    "korba": "unknown",
    "shivpuri": "unknown",
    "nangloi_jat": "unknown",
    "madanapalle": "unknown",
    "thoothukudi": "unknown",
    "nagercoil": "unknown",
    "gaya": "unknown",
    "jammu[16]": "unknown",
    "kakinada": "unknown",
    "dewas": "unknown",
    "bhalswa_jahangir_pur": "unknown",
    "baranagar": "unknown",
    "firozabad": "unknown",
    "phusro": "unknown",
    "guna": "unknown",
    "thane": "unknown",
    "etawah": "unknown",
    "vasai_virar": "unknown",
    "pallavaram": "unknown",
    "morena": "unknown",
    "ballia": "unknown",
    "burhanpur": "unknown",
    "phagwara": "unknown",
    "mau": "unknown",
    "mangalore": "unknown",
    "alwar": "unknown",
    "mahbubnagar": "unknown",
    "maheshtala": "unknown",
    "hazaribagh": "unknown",
    "bihar_sharif": "unknown",
    "faridabad": "unknown",
    "tenali": "unknown",
    "amroha": "unknown",
    "medininagar": "unknown",
    "rajahmundry[19][20]": "unknown",
    "bhilai": "unknown",
    "moradabad": "unknown",
    "machilipatnam": "unknown",
    "mira_bhayandar": "unknown",
    "pali": "unknown",
    "mehsana": "unknown",
    "imphal": "unknown",
    "sambalpur": "unknown",
    "ujjain": "unknown",
    "madhyamgram": "unknown",
    "jamalpur[36]": "unknown",
    "gangtok": "unknown",
    "anand": "unknown",
    "dehradun": "unknown",
    "srikakulam": "unknown",
    "darbhanga": "unknown",
    "nizamabad": "unknown",
    "dehri[30]": "unknown",
    "jorhat": "unknown",
    "kumbakonam": "unknown",
    "haldia": "unknown",
    "loni": "unknown",
    "pimpri_chinchwad": "unknown",
    "nanded": "unknown",
    "kirari_suleman_nagar": "unknown",
    "jaunpur": "unknown",
    "bilaspur": "unknown",
    "sambhal": "unknown",
    "rourkela": "unknown",
    "dharmavaram": "unknown",
    "nellore[14][15]": "unknown",
    "visakhapatnam[4]": "unknown",
    "karawal_nagar": "unknown",
    "avadi": "unknown",
    "bhimavaram": "unknown",
    "bardhaman": "unknown",
    "silchar": "unknown",
    "kavali": "unknown",
    "tezpur": "unknown",
    "ramagundam[27]": "unknown",
    "yamunanagar": "unknown",
    "sri_ganganagar": "unknown",
    "sasaram[30]": "unknown",
    "sikar": "unknown",
    "bally": "unknown",
    "bhiwani": "unknown",
    "rampur": "unknown",
    "uluberia": "unknown",
    "sangli_miraj_&_kupwad": "unknown",
    "hosur": "unknown",
    "bikaner": "unknown",
    "shahjahanpur": "unknown",
    "sultan_pur_majra": "unknown",
    "bharatpur": "unknown",
    "tadepalligudem": "unknown",
    "tinsukia": "unknown",
    "salem": "unknown",
    "mathura": "unknown",
    "guntur[13]": "unknown",
    "hubli_dharwad": "unknown",
    "chittoor[28]": "unknown",
    "tiruvottiyur": "unknown",
    "ahmednagar": "unknown",
    "fatehpur": "unknown",
    "bhilwara": "unknown",
    "kharagpur": "unknown",
    "bettiah[33]": "unknown",
    "bhind": "unknown",
    "bokaro": "unknown",
    "raebareli": "unknown",
    "pudukkottai": "unknown",
    "panipat": "unknown",
    "tadipatri": "unknown",
    "orai": "unknown",
    "raurkela_industrial_township": "unknown",
    "katni": "unknown",
    "chandrapur": "unknown",
    "kolhapur": "unknown"
}

# Define semantic column types (for ColumnTransformer to scale numerical and encode categorical columns)
NUMERICAL_COLUMNS = ["income", "age", "experience", "current_job_yrs", "current_house_yrs", "state_default_rate"]
CATEGORICAL_COLUMNS = ["house_ownership", "job_stability", "city_tier", "profession", "city", "state"]
BOOLEAN_COLUMNS = ["risk_flag", "married", "car_ownership"]

# Define the categories for the nominal column "house_ownership" (for OneHotEncoder)
NOMINAL_COLUMN_CATEGORIES = [["norent_noown", "owned", "rented"]]  # OneHotEncoder requires list of lists even for single column

# Define the explicit order of categories for all ordinal columns (for OrdinalEncoder)
ORDINAL_COLUMN_ORDERS = [
    ["variable", "moderate", "stable", "very_stable"],  # Order for job_stability
    ["unknown", "tier_3", "tier_2", "tier_1"]  # Order for city_tier
]

# Define the columns to keep after preprocessing as model input (for custom FeatureSelector)
COLUMNS_TO_KEEP = [
    "income", "age", "experience", "current_job_yrs", "current_house_yrs", "state_default_rate", "house_ownership_owned", 
    "house_ownership_rented", "job_stability", "city_tier", "married", "car_ownership"
]

# Store the best Random Forest hyperparameter values identified with random search (for RandomForestClassifier)
RF_BEST_PARAMS = {
  "n_estimators": 225,
  "max_depth": 26,
  "min_samples_split": 2,
  "min_samples_leaf": 1,
  "max_features": np.float64(0.12974565961049356),
  "class_weight": "balanced"
}

# --- Constants for App ---
# Lists of categorical string labels (in format expected by the pipeline)
MARRIED_LABELS = ["single", "married"]
CAR_OWNERSHIP_LABELS = ["yes", "no"]
HOUSE_OWNERSHIP_LABELS = ["rented", "owned", "norent_noown"]  
PROFESSION_LABELS = [
    "air_traffic_controller", "analyst", "architect", "army_officer", "artist", "aviator",
    "biomedical_engineer", "chartered_accountant", "chef", "chemical_engineer", "civil_engineer",
    "civil_servant", "comedian", "computer_hardware_engineer", "computer_operator", "consultant",
    "dentist", "design_engineer", "designer", "drafter", "economist", "engineer",
    "fashion_designer", "financial_analyst", "firefighter", "flight_attendant", "geologist",
    "graphic_designer", "hotel_manager", "industrial_engineer", "lawyer", "librarian",
    "magistrate", "mechanical_engineer", "microbiologist", "official", "petroleum_engineer",
    "physician", "police_officer", "politician", "psychologist", "scientist", "secretary",
    "software_developer", "statistician", "surgeon", "surveyor", "technical_writer",
    "technician", "technology_specialist", "web_designer"
]
CITY_LABELS = [
    "adoni", "agartala", "agra", "ahmedabad", "ahmednagar", "aizawl", "ajmer", "akola", "alappuzha", "aligarh",
    "allahabad", "alwar", "ambala", "ambarnath", "ambattur", "amravati", "amritsar", "amroha", "anand", "anantapur",
    "anantapuram[24]", "arrah", "asansol", "aurangabad", "aurangabad[39]", "avadi", "bahraich", "ballia", "bally",
    "bangalore", "baranagar", "barasat", "bardhaman", "bareilly", "bathinda", "begusarai", "belgaum", "bellary",
    "berhampore", "berhampur", "bettiah[33]", "bhadravati", "bhagalpur", "bhalswa_jahangir_pur", "bharatpur",
    "bhatpara", "bhavnagar", "bhilai", "bhilwara", "bhimavaram", "bhind", "bhiwandi", "bhiwani", "bhopal",
    "bhubaneswar", "bhusawal", "bidar", "bidhannagar", "bihar_sharif", "bijapur", "bikaner", "bilaspur", "bokaro",
    "bongaigaon", "bulandshahr", "burhanpur", "buxar[37]", "chandigarh_city", "chandrapur", "chapra", "chennai",
    "chinsurah", "chittoor[28]", "coimbatore", "cuttack", "danapur", "darbhanga", "davanagere", "dehradun",
    "dehri[30]", "delhi_city", "deoghar", "dewas", "dhanbad", "dharmavaram", "dhule", "dibrugarh", "dindigul",
    "durg", "durgapur", "eluru[25]", "erode[17]", "etawah", "faridabad", "farrukhabad", "fatehpur", "firozabad",
    "gandhidham", "gandhinagar", "gangtok", "gaya", "ghaziabad", "giridih", "gopalpur", "gorakhpur", "gudivada",
    "gulbarga", "guna", "guntakal", "guntur[13]", "gurgaon", "guwahati", "gwalior", "hajipur[31]", "haldia",
    "hapur", "haridwar", "hazaribagh", "hindupur", "hospet", "hosur", "howrah", "hubli_dharwad", "hyderabad",
    "ichalkaranji", "imphal", "indore", "jabalpur", "jaipur", "jalandhar", "jalgaon", "jalna", "jamalpur[36]",
    "jammu[16]", "jamnagar", "jamshedpur", "jaunpur", "jehanabad[38]", "jhansi", "jodhpur", "jorhat", "junagadh",
    "kadapa[23]", "kakinada", "kalyan_dombivli", "kamarhati", "kanpur", "karawal_nagar", "karaikudi", "karimnagar",
    "karnal", "katihar", "katni", "kavali", "khammam", "khandwa", "kharagpur", "khora,_ghaziabad",
    "kirari_suleman_nagar", "kishanganj[35]", "kochi", "kolhapur", "kolkata", "kollam", "korba", "kota[6]",
    "kottayam", "kozhikode", "kulti", "kumbakonam", "kurnool[18]", "latur", "loni", "lucknow", "ludhiana",
    "machilipatnam", "madanapalle", "madhyamgram", "madurai", "mahbubnagar", "maheshtala", "malda", "malegaon",
    "mango", "mangalore", "mathura", "mau", "medininagar", "meerut", "mehsana", "mira_bhayandar", "mirzapur",
    "miryalaguda", "moradabad", "morbi", "morena", "motihari[34]", "mumbai", "munger", "muzaffarnagar",
    "muzaffarpur", "mysore[7][8][9]", "nadiad", "nagaon", "nagercoil", "nagpur", "naihati", "nanded", "nandyal",
    "nangloi_jat", "narasaraopet", "nashik", "navi_mumbai", "nellore[14][15]", "new_delhi", "nizamabad", "noida",
    "north_dumdum", "ongole", "orai", "ozhukarai", "pali", "pallavaram", "panchkula", "panipat", "panihati",
    "panvel", "parbhani", "patiala", "patna", "phagwara", "phusro", "pimpri_chinchwad", "pondicherry",
    "proddatur", "pudukkottai", "pune", "purnia[26]", "raebareli", "raichur", "raiganj", "raipur",
    "rajahmundry[19][20]", "rajkot", "rajpur_sonarpur", "ramagundam[27]", "ramgarh", "rampur", "ranchi", "ratlam",
    "raurkela_industrial_township", "rewa", "rohtak", "rourkela", "sagar", "saharanpur", "saharsa[29]", "salem",
    "sambalpur", "sambhal", "sangli_miraj_&_kupwad", "sasaram[30]", "satara", "satna", "secunderabad",
    "serampore", "shahjahanpur", "shimla", "shimoga", "shivpuri", "sikar", "silchar", "siliguri", "singrauli",
    "sirsa", "siwan[32]", "solapur", "sonipat", "south_dumdum", "sri_ganganagar", "srikakulam", "srinagar",
    "sultan_pur_majra", "surat", "surendranagar_dudhrej", "suryapet", "tadipatri", "tadepalligudem", "tenali",
    "tezpur", "thane", "thanjavur", "thiruvananthapuram", "thoothukudi", "thrissur", "tinsukia",
    "tiruchirappalli[10]", "tirunelveli", "tirupati[21][22]", "tiruppur", "tiruvottiyur", "tumkur", "udaipur",
    "udupi", "ujjain", "ulhasnagar", "uluberia", "unnao", "vadodara", "varanasi", "vasai_virar", "vellore",
    "vijayawada", "vijayanagaram", "visakhapatnam[4]", "warangal[11][12]", "yamunanagar"
]
STATE_LABELS = [
    "andhra_pradesh", "assam", "bihar", "chandigarh", "chhattisgarh",
    "delhi", "gujarat", "haryana", "himachal_pradesh", "jammu_and_kashmir",
    "jharkhand", "karnataka", "kerala", "madhya_pradesh", "maharashtra",
    "manipur", "mizoram", "odisha", "puducherry", "punjab", "rajasthan",
    "sikkim", "tamil_nadu", "telangana", "tripura", "uttar_pradesh",
    "uttar_pradesh[5]", "uttarakhand", "west_bengal"
]
